export const data=[
    {
        name:"clear",
        id:1,
        display:"AC"
    },
    {
        name:"clearOne",
        id:2,
        display:"C"
    },
    {
        name:"devide",
        id:3,
        isNUmber:false,
        display:"/"
    },
    
    {
        name:"seven",
        id:5,
        isNUmber:true,
        isNUmber:true,
        display:"7"
        
    },
    {
        name:"eight",
        id:6,
        isNUmber:true,
        display:"8"
    },
    {
        name:"nine",
        id:7,
        isNUmber:true,
        display:"9"
    },
    {
        name:"multiply",
        id:4,
        isNUmber:false,
        display:"*"
    },
    
    {
        name:"four",
        id:9,
        isNUmber:true,
        display:"4"
    },
    {
        name:"five",
        id:10,
        isNUmber:true,
        display:"5"
    },
    {
        name:"six",
        id:11,
        isNUmber:true,
        display:"6"
    },
    {
        name:"minus",
        id:8,
        isNUmber:false,
        display:"-"
    },
    
    {
        name:"one",
        id:13,
        isNUmber:true,
        display:"1"
    },
    {
        name:"",
        id:14,
        isNUmber:true,
        display:"2"
    },
    {
        name:"three",
        id:15,
        isNUmber:true,
        display:"3"
    },
    {
        name:"plus",
        id:12,
        isNUmber:false,
        display:"+"
    },
    
    {
        name:"zero",
        id:17,
        isNUmber:true,
        display:"0"
    },
    {
        name:"dot",
        id:18,
        isNUmber:true,
        display:"."
    },
    {
        name:"total",
        id:16,
        display:"="
    },
]